name: Linting and Tests on PR

on:
  pull_request:
    branches:
      - main  # You can change this to the target branch of your PR
    types:
      - opened
      - synchronize
      - reopened

jobs:
  lint_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install pipenv
          pipenv sync --dev

      - name: Run Flake8 linting
        run: |
          flake8 .  # Run Flake8 to check for linting issues
